### ISSUE TITLE
npx frost-gen --help throws error

### ISSUE THREAD

**Issue by DevAndromeda** [DevSnowflake/frost#4]
Running `npx frost-gen --help` throws error saying `typescript not found`. Maybe we should consider installing `typescript` under `dependencies` rather than `devDependencies` or look for other solutions?

![image](https://user-images.githubusercontent.com/46562212/142671674-a87d769f-c06a-4ce9-9241-a29c804aecb2.png)

**Comment by rhygg** [comment]
Yeah, it should be installing the module regardless. 🤔

**Comment by rhygg** [comment]
Moving it from `devDependencies` into `dependencies` should do the thing.

**Comment by rhygg** [comment]
Issue fixed most probably in commit [72](https://github.com/DevSnowflake/frost/commit/57db4f25ef36b4e82f093ff839fa467c84e60b86)
